### ISSUE TITLE
Auto-determine `stable` version for GCP

### ISSUE THREAD

**Issue by VimCommando** [sunileman/ElasticKonductor#7]
<img width="1845" alt="image" src="https://user-images.githubusercontent.com/1674688/222792333-49d3f0ab-434e-4d76-9439-f03c7e74b6e5.png">

I've run into this a few times, after I haven't deployed to GCP for a week the `STABLE` version has moved.

It would be great if GCP can auto-detect what the most recent patch version is. This seems like a tough target to keep up-to-date in `variables.tf` all the time.

https://github.com/sunileman/1ClickECK/blob/fdac47f4f7d0265ea0aaa80d35454d3b9d600ef7/gcp/variables.tf#L23-L27

**Comment by sunilemanjee** [comment]
@VimCommando  the automation actually defaults to stable release channel for GKE.  therefore that field is optional.  I'll remove it and test functionality.  I believe this should be fine.

https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels

**Comment by sunilemanjee** [comment]
@VimCommando I can completely remove version and it would use the stable release version.  Or I can add fuzzy version like this

```
resource "google_container_node_pool" "my_node_pool" {
  // other configuration options

  version = "~1.18"
}

**Comment by sunilemanjee** [comment]
Note - for fuzzy I will need to use data source

https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_engine_versions

```
data "google_container_engine_versions" "versions" {
  location = "us-central1"
}

resource "google_container_node_pool" "my_node_pool" {
  // other configuration options

  version = "${data.google_container_engine_versions.versions.latest_version_prefix}"
}

**Comment by sunilemanjee** [comment]
testing the following change.

```
variable "gke_version" {
  description = "GKE Version"
  type        = string
  
  default     = "1.24."
}
```

What this will do is take the base version specified by user and then fetch the latest min release (stable) for the zone

**Comment by sunilemanjee** [comment]
My test completed with success.   Specify only major version and allowing the automation to fetch the minor


```
root@ip-10-0-9-248:~/github/1ClickECK# kubectl get nodes
NAME                                                  STATUS   ROLES    AGE     VERSION
gke-oneclickeck-sunman-fresh-k-kibana-81150ea5-j72f   Ready    <none>   32m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-k-kibana-a6703feb-xflj   Ready    <none>   32m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-k-kibana-fdeccbda-b83v   Ready    <none>   32m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-k-master-d4cea243-zds4   Ready    <none>   39m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-k-master-e233361a-qtt6   Ready    <none>   38m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-k-master-e4459f56-m6t7   Ready    <none>   39m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-kiw-util-39e151af-5lpw   Ready    <none>   3m37s   v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-kiwi-hot-1016ea58-rr23   Ready    <none>   30m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-kiwi-hot-94ab27e8-p0vf   Ready    <none>   30m     v1.24.10-gke.1200
gke-oneclickeck-sunman-fresh-kiwi-hot-9cc37563-kcr4   Ready    <none>   30m     v1.24.10-gke.1200
```

**Comment by sunileman** [comment]
Fixed in `.48`.  Pushed.
